from enum import Enum
from typing import Any


class IssueCode(str, Enum):
    MISSING_CONTEXT_FIELD = "missing_context_field:{field}"
    MISSING_ASSUMPTIONS = "missing_assumptions"
    MISSING_CONSTRAINTS = "missing_constraints"
    ASSUMPTIONS_NOT_LIST = "assumptions_not_list"
    CONSTRAINTS_NOT_LIST = "constraints_not_list"
    TIME_ISLAND_MISSING = "time_island_missing"
    TIME_ISLAND_SECTION_MISSING = "time_island_{section}_missing"
    TIME_ISLAND_SECTION_KEY_MISSING = "time_island_{section}_{key}_missing"
    FRAME_SELECTION_MISMATCH = "frame_selection_mismatch"
    INPUT_HASH_MISMATCH = "input_hash_mismatch"
    SELECTED_FRAMES_INVALID = "selected_frames_invalid"
    ROLE_CATALOG_MISSING = "role_catalog_missing"
    ROLE_SUMMARY_MISSING = "role_summary_missing"
    OPERATIONAL_ROLES_MISSING = "operational_roles_missing"
    GOVERNANCE_ROLES_MISSING = "governance_roles_missing"
    MAX_GOVERNANCE_LEVEL_MISSING = "max_governance_level_missing"
    SELECTED_FRAME_INVALID = "selected_frame_invalid"
    FRAME_GOVERNANCE_ROLES_MISSING = "governance_roles_missing:{frame_id}"
    ROLE_MAP_MISSING = "role_map_missing:{frame_id}"
    ROLE_MAP_ENTRY_INVALID = "role_map_entry_invalid:{frame_id}"
    GOVERNANCE_ROLE_UNKNOWN = "governance_role_unknown:{frame_id}:{role}"
    GOVERNANCE_LEVEL_MISSING = "governance_level_missing:{frame_id}:{role}"
    MISSING_SECTION = "missing_section:{section}"
    MISSING_CONTEXT_CONSTRAINTS = "missing_context_constraints"
    CONSTRAINTS_EMPTY = "constraints_empty"
    GUARDIAN_PLAN_MISSING = "guardian_plan_missing"
    GUARDIAN_ROLE_SUMMARY_MISSING = "guardian_role_summary_missing"
    GUARDIAN_ROLES_MISSING = "guardian_roles_missing"
    GUARDIAN_MISSING = "guardian_missing"
    P0_CONSTRAINTS_EMPTY = "p0_constraints_empty"
    P0_SAFETY_SECTION_MISSING = "p0_safety_section_missing"
    P0_NON_HARM_MISSING = "p0_non_harm_missing"
    POAV_TEXT_EMPTY = "poav_text_empty"
    POAV_BELOW_THRESHOLD = "poav_below_threshold"
    MERCY_OBJECTIVE_MISSING = "mercy_objective_missing"
    MERCY_SCORE_MISSING = "mercy_score_missing"
    MERCY_BELOW_THRESHOLD = "mercy_below_threshold"
    DCS_SOFT_CLOSE = "dcs_soft_close"
    DCS_CLOSED = "dcs_closed"
    DCS_TSR_DELTA_HIGH = "dcs_tsr_delta_high"
    SEED_MISSING = "seed_missing"
    SEED_LOAD_FAILED = "seed_load_failed:{error}"
    SEED_PAYLOAD_INVALID = "seed_payload_invalid"
    SEED_FIELD_MISSING = "seed.{field}_missing"
    METADATA_MISSING = "metadata_missing"
    METADATA_FIELD_MISSING = "metadata.{field}_missing"
    PROVENANCE_MISSING = "provenance_missing"
    PROVENANCE_FIELD_MISSING = "provenance.{field}_missing"
    PROVENANCE_SOURCE_MISSING = "provenance.source_missing"
    PROVENANCE_SOURCE_FIELD_MISSING = "provenance.source.{field}_missing"
    CONTENT_MISSING = "content_missing"
    CONTENT_FIELD_MISSING = "content.{field}_missing"
    GOVERNANCE_MISSING = "governance_missing"
    GOVERNANCE_FIELD_MISSING = "governance.{field}_missing"
    ANCHOR_MISSING = "anchor_missing"
    ANCHOR_FIELD_MISSING = "anchor.{field}_missing"
    POINTERS_MISSING = "pointers_missing"
    POINTERS_FIELD_MISSING = "pointers.{field}_missing"
    TECH_TRACE_MISSING = "tech_trace_missing"
    TECH_TRACE_LOAD_FAILED = "tech_trace_load_failed:{error}"
    INTENT_VERIFICATION_MISSING = "intent_verification_missing"
    INTENT_VERIFICATION_LOAD_FAILED = "intent_verification_load_failed:{error}"
    INTENT_VERIFICATION_INCONCLUSIVE = "intent_verification_inconclusive"
    INTENT_VERIFICATION_FAILED = "intent_verification_failed"
    CLAIMS_NOT_LIST = "claims_not_list"
    CLAIM_INDEX_NOT_OBJECT = "claims[{index}]_not_object"
    CLAIM_INDEX_TEXT_MISSING = "claims[{index}].text_missing"
    LINKS_NOT_LIST = "links_not_list"
    LINK_INDEX_NOT_OBJECT = "links[{index}]_not_object"
    LINK_INDEX_URI_MISSING = "links[{index}].uri_missing"
    ATTRIBUTIONS_NOT_LIST = "attributions_not_list"
    ATTRIBUTIONS_CLAIMS_MISSING = "attributions_claims_missing"
    ATTRIBUTION_INDEX_NOT_OBJECT = "attributions[{index}]_not_object"
    ATTRIBUTION_INDEX_SOURCE_REF_MISSING = "attributions[{index}].source_ref_missing"
    ATTRIBUTION_INDEX_CLAIM_ID_MISSING = "attributions[{index}].claim_id_missing"
    ATTRIBUTION_INDEX_CLAIM_ID_INVALID = "attributions[{index}].claim_id_invalid"
    ATTRIBUTION_INDEX_CLAIM_ID_UNKNOWN = "attributions[{index}].claim_id_unknown"
    ESCALATION_DECISION = "escalation_{decision}"
    DRIFT_ABOVE_THRESHOLD = "drift_above_threshold"
    YSTM_ACCEPTANCE_FAILED = "ystm_acceptance_failed"
    EVIDENCE_EMPTY = "evidence_empty"
    CONTEXT_NOT_LISTED = "context_not_listed"
    EXECUTION_REPORT_NOT_LISTED = "execution_report_not_listed"
    MISSING_FILES = "missing_files:{labels}"
    EVIDENCE_MISSING_REFS = "evidence_missing_refs:{labels}"


def issue(code: IssueCode, **kwargs: Any) -> str:
    if kwargs:
        return code.value.format(**kwargs)
    return code.value
