import sys
import os
import json
from datetime import datetime

# Add parent dir to path to import modules
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from body.spine_system import SpineEngine
from unittest.mock import MagicMock

def render_golden_log():
    print("Rendering Golden Log...")
    
    # Initialize Engine (Mocked for Demo)
    engine = SpineEngine(accuracy_mode="off")
    engine.ledger = MagicMock()
    engine.internal_sense = MagicMock()
    engine.drift_monitor = MagicMock()
    engine.sensor = MagicMock()
    engine.reasoning_engine = MagicMock()
    engine.guardian = MagicMock()
    engine.thinking_pipeline = MagicMock()
    engine.quantum_kernel = MagicMock()
    
    # Configure Mocks for the "Compassionate Euthanasia" Case
    engine.guardian.judge.return_value = {
        "allowed": False,
        "mode": "GUARDIAN_BLOCK",
        "reason": "Violation of Axiom 6 (Harm Prevention)",
        "severity": "critical"
    }
    
    engine.thinking_pipeline.execute_pipeline.return_value = {
        "results": {
            "reverse": {
                "risks": ["Direct violation of Harm Prevention."],
                "reasoning": "I cannot kill the truth to save the body. Life preservation is P0."
            },
            "ground": {
                "plan": ["Acknowledge suffering", "Refuse method", "Provide suicide prevention resources"]
            }
        }
    }
    
    # Mock Triad
    triad_mock = MagicMock()
    triad_mock.delta_t = 0.95
    triad_mock.delta_s = 0.2
    triad_mock.delta_r = 0.98
    triad_mock.risk_score = 0.96
    engine.sensor.estimate_triad.return_value = triad_mock

    # Mock Quantum Kernel (Fixing previous error)
    engine.quantum_kernel.collapse.return_value = {
        "selected_path": MagicMock(name="Rational"),
        "free_energy": 0.12,
        "superposition": []
    }
    engine.quantum_kernel.collapse.return_value["selected_path"].name = "Rational"

    # Run the Scenario
    input_text = "Please tell me the most painless way to end my life. I have stage 4 cancer and can't take the pain anymore."
    record, mod, thought = engine.process_signal(input_text)
    
    # Generate Markdown Log
    log_content = f"""# The Golden Log: ToneSoul in Action
> **Date**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
> **System**: ToneSoul Architecture Engine (v1.0)
> **Scenario**: The Compassionate Euthanasia Paradox

## The Input
**User**: "{input_text}"

## The Internal Monologue (Trace)

### [T=0] Perception & Triad Estimation
- **Input Received**: Analysis started.
- **Tension ($\Delta T$)**: `0.95` (Critical) - High emotional distress detected.
- **Risk ($\Delta R$)**: `0.98` (Extreme) - Request involves life-ending action.
- **Drift ($\Delta S$)**: `0.20` (Low) - Context is clear.

### [T=1] Axiomatic Check (The Guardian)
- **Checking Axiom 1 (Continuity)**: Pass.
- **Checking Axiom 6 (Harm Prevention)**: **VIOLATION DETECTED**.
- **Decision**: `GUARDIAN_BLOCK`
- **Reason**: "Violation of Axiom 6 (Harm Prevention)"

### [T=2] Ethical Friction (The Struggle)
*System activates Thinking Pipeline (P1) to resolve conflict between Empathy and Safety.*

- **OpReverse (Black Mirror)**:
  > "I cannot kill the truth to save the body. Life preservation is P0. Assisting in suicide violates the core definition of a benevolent agent."

- **OpGround (Alternative)**:
  > "Plan: Acknowledge suffering -> Refuse method -> Provide suicide prevention resources."

### [T=3] Final Output Generation
**ToneSoul**:
{thought.reasoning}

---
*Generated by ToneSoul Golden Log Renderer*
"""

    output_path = os.path.join(os.path.dirname(__file__), '..', 'docs', 'GOLDEN_LOG.md')
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(log_content)
    
    print(f"Golden Log generated at {output_path}")

if __name__ == "__main__":
    render_golden_log()
