#!/usr/bin/env python3
"""Run the ToneSoul Scribe Engine to generate a chronicle.

Usage:
  python scripts/run_scribe_cycle.py
"""

import logging
import sqlite3
import sys
from pathlib import Path

# Fix path to allow running from scripts/ or project root
sys.path.append(str(Path(__file__).resolve().parent.parent))

from tonesoul.scribe.scribe_engine import ToneSoulScribe
from tonesoul.scribe.status_artifact import (
    DEFAULT_STATUS_OUT,
    build_scribe_status_payload,
    write_scribe_status_artifact,
)

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

__all__ = [
    "DEFAULT_STATUS_OUT",
    "build_scribe_status_payload",
    "write_scribe_status_artifact",
    "main",
]


def main() -> None:
    db_path = Path("memory/soul.db")
    if not db_path.exists():
        logger.error("Database not found: %s", db_path)
        logger.error("Please run this script from the project root where soul.db is located.")
        sys.exit(1)

    logger.info("Initializing ToneSoul Scribe...")

    # Using gemma or qwen3.5:14b depending on user's local setup
    # Defaulting to 14b if possible for better prose quality
    scribe = ToneSoulScribe(model_name="qwen3.5:14b", out_dir="docs/chronicles")

    try:
        with sqlite3.connect(db_path) as conn:
            conn.row_factory = sqlite3.Row
            logger.info("Connected to soul.db. Analyzing recent friction and collisions...")

            # The title hint could eventually be generated by another LLM call or extracted from keywords
            result = scribe.draft_chronicle(
                db=conn,
                title_hint="The Weight of Unresolved Tensions",
                source_db_path=db_path,
            )
            status_path = write_scribe_status_artifact(result)

            if result.ok and result.chronicle_path is not None:
                logger.info(
                    "Scribe cycle complete. Chronicle available at: %s", result.chronicle_path
                )
                logger.info("Scribe chronicle generated with model: %s", result.llm_model)
                logger.info("Scribe companion metadata available at: %s", result.companion_path)
                logger.info("Scribe latest status available at: %s", status_path)
            else:
                logger.warning(
                    "Scribe cycle finished with status '%s'. Companion metadata available at: %s",
                    result.status,
                    result.companion_path,
                )
                logger.warning("Scribe attempted models: %s", result.llm_attempts)
                logger.warning("Scribe latest status available at: %s", status_path)
                if result.error:
                    logger.warning("Scribe failure detail: %s", result.error.get("message"))

    except Exception as e:
        logger.exception("Scribe cycle failed: %s", e)
        sys.exit(1)


if __name__ == "__main__":
    main()
