import argparse
import json
import os
from typing import Dict

from ..ystm.diff import compute_batch_diff
from ..ystm.schema import as_clean_dict
from ..ystm.storage import load_nodes_payload


def _workspace_root() -> str:
    return os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Compute semantic diff between YSTM node sets.")
    parser.add_argument("--before", required=True, help="Path to nodes.json (before).")
    parser.add_argument("--after", required=True, help="Path to nodes.json (after).")
    parser.add_argument("--rationale", default="Diff generated by run_ystm_diff.")
    parser.add_argument(
        "--source-grade",
        choices=["A", "B", "C"],
        default="C",
        help="Evidence grade for the semantic diff.",
    )
    parser.add_argument(
        "--source-patch-id", default=None, help="Optional source patch id for the diff."
    )
    parser.add_argument(
        "--trace-level",
        choices=["standard", "full"],
        default="standard",
        help="Trace level tag for the semantic diff.",
    )
    parser.add_argument("--output", help="Output path for semantic_diff.json.")
    return parser


def main() -> Dict[str, str]:
    parser = build_arg_parser()
    args = parser.parse_args()

    before_nodes, _ = load_nodes_payload(args.before)
    after_nodes, _ = load_nodes_payload(args.after)
    before_map = {node.id: node for node in before_nodes}
    after_map = {node.id: node for node in after_nodes}

    diff = compute_batch_diff(
        before_map,
        after_map,
        rationale=args.rationale,
        source_grade=args.source_grade,
        source_patch_id=args.source_patch_id,
        trace_level=args.trace_level,
    )
    payload = as_clean_dict(diff)

    output_path = args.output
    if not output_path:
        output_dir = os.path.join(_workspace_root(), "generated", "ystm_diff")
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, f"{diff.id}.json")
    else:
        output_path = os.path.abspath(output_path)
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
    return {"semantic_diff": output_path}


if __name__ == "__main__":
    paths = main()
    print(f"semantic_diff.json: {paths['semantic_diff']}")
